Processing data in model
kazim110/blog_app1 pull request #2
Opened 2023-11-08 08:49 UTC by kazim110

I have added custom methods to the models `User`, `Post`, `Comment`, and `Like` that fulfill the following requirements:

- **Users**: Added a `recent_posts` method to retrieve the 3 most recent posts for a given user.

- **Posts**: Added an `update_posts_counter` method to update the posts counter for a user. Also added a `recent_comments` method to retrieve the 5 most recent comments for a given post.

- **Comments**: Added an `update_comments_counter` method to update the comments counter for a post.

- **Likes**: Added an `update_likes_counter` method to update the likes counter for a post.

These methods are designed to enhance the functionality and data integrity of our application.

2023-11-08 09:10 UTC, gemmen29 requested changes
Hi @kazim110, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 09:10 UTC, gemmen29 commented on app/models/user.rb
> +  end
- [ ] Kindly use the order query before the limit query as now will lead to a result that doesn't match this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project_v1_1.md#:~:text=A%20method%20that%20returns%20the%203%20most%20recent%20posts%20for%20a%20given%20user.). so it will be like:
``` ruby
posts.order(created_at: :desc).limit(3)
```

2023-11-08 09:10 UTC, gemmen29 commented on app/models/post.rb
> +  end
- [ ] [OPTIONAL] Kindly use the ActiveRecord `after_save` to call the `update_posts_counter` so this method will be called every time a new post has been saved to the database, then make the `update_posts_counter` method private. Also please do the same with `update_liks_counter` in the `Like` model and `update_comments_counter` in the `Comment` model

2023-11-08 09:56 UTC, OLIPLICHE approved these changes
Hi @kazim110, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Applied the changes requested by the previous review(✅)) 👏
- Created and sets up associations between models👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 09:57 UTC, merged

2024-01-13 13:42 UTC, Nemwel-Boniface reviewed
## Hello @kazim110      :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._