Add views, controllers and their actions
kazim110/blog_app1 pull request #4
Opened 2023-11-14 05:55 UTC by kazim110

### Changes Made:
Added views and controllers for Users and Posts.
Implemented show and index actions for both resources.
### Details:
### Users:

- Created user views (users/show.html.erb, users/index.html.erb).
- Implemented UsersController with show and index actions.

### Posts:

- Created post views (posts/show.html.erb, posts/index.html.erb).
- Implemented PostsController with show and index actions.

2023-11-14 06:29 UTC, Ibizugbe requested changes
Hi @kazim110 👋🏼👋🏼👋🏼, 

![request change](https://github.com/kazim110/blog_app/assets/64643995/0d7d0f0b-4ac8-43e5-823b-6f3fb530adce)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] User and Post controller have been created with their corresponding index and show actions👍🏼.
- [x] The corresponding views for the controller actions have been created👍🏼.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Kindly ensure your commit messages are always capitalized as this is a more professional practice👍🏼.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-14 06:29 UTC, Ibizugbe commented on config/routes.rb
> +  end
Nice job so far👍🏼. just as required for this milestone, kindly ensure your route, only exposes the 4 URL path as required. Apart from this being a requirement, limiting routes to only essential actions can enhance security by reducing the surface area for potential attacks. If certain actions are not needed for a resource, it's best not to expose them.


<img width="796" alt="image" src="https://github.com/kazim110/blog_app/assets/64643995/c1c1e6d2-1664-4d7d-94b0-d5479d6f2ea8">

```suggestion
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
```

2023-11-14 07:56 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @kazim110 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All route are now correct :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-14 07:56 UTC, tresorsawasawa commented on config/routes.rb
**README.md** file:

- [ **OPTIONAL** ] I think it would be better if you completetly remove the `## Live Demo `  section from your README as your application is not deployed yet. This is for all project requirements and to make your documentation looks more professional.
![image](https://github.com/kazim110/blog_app/assets/83042742/9653ad79-5f3a-443f-9cb8-730227c114e8)

- [ **OPTIONAL** ] to make your documentation looks more professional and descriptive, I think it would be better if you update your `Getting started` section by completing each sub-section with correct and appropriate information such as how to `access` the clone dir, `run` your app, `install bundles`, `run tests` if exist,...
To help you, I recommend you refer **[this gist_file as template](https://gist.github.com/tresorsawasawa/4cde69cff1b40161b9de380f9891f415)**.

2023-11-14 08:11 UTC, merged

2024-01-19 14:39 UTC, Gambit142 reviewed
Hi @kazim110 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Setup linters correctly ✔️ 
- Created `Posts` and `Users` controller ✔️ 
- Created necessary routes ✔️ 
- Created view files for the controllers ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._