Fix n+1 problem in index of users
kazim110/blog_app1 pull request #8
Opened 2023-11-22 10:34 UTC by kazim110

2023-11-24 12:53 UTC, Whoistolu requested changes
Hi @kazim110 and @Nessrine88 ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

- [ ] [OPTIONAL] I would like to advice that you consider breaking down your scenario into smaller, more focused tests. Each test should ideally focus on a specific aspect of the feature. For example, you could have separate tests for post details, comments, and the presence of the "New Comment" link.
- [ ] [OPTIONAL] Also, I will like you to consider making your expectations more descriptive. For example, instead of checking for the presence of "Post#1", you might check for the post's actual content or a more descriptive identifier.
``` ruby
expect(page).to have_content("Post Content: This is the content of the post")
```

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-24 12:53 UTC, Whoistolu commented on spec/integrations/users_index_spec.rb
> +end
- [ ] [REQUIRED] For the user index page, kindly add tests that redirects to the user's show page when you click on a user. This is part of the project requirements.

2023-11-24 12:53 UTC, Whoistolu commented on spec/integrations/users_show_spec.rb
> +end
- [ ] [REQUIRED] Kindly add the following tests as they have been omitted from the User show page spec file and they are hard requirements
- Tests that asserts you can see the user's profile picture
- Tests that asserts you can see the number of posts the user has written
- Tests that asserts you can see the user's first 3 posts
- Tests that asserts you can see a button that lets me view all of a user's posts.
- Tests that redirects to the post's show page when you click on a user's post
- Tests that redirects to the user's post's index page when you click on a **see all posts**.

- [ ] [OPTIONAL] I would like to advice that you consider breaking down your scenario into smaller, more focused tests. Each test should ideally focus on a specific aspect of the feature. For example, you could have separate tests for post details, comments, and the presence of the "New Comment" link.
- [ ] [OPTIONAL] Also, I will like you to consider making your expectations more descriptive. For example, instead of checking for the presence of "Post#1", you might check for the post's actual content or a more descriptive identifier.
``` ruby
expect(page).to have_content("Post Content: This is the content of the post")
```

2023-11-24 12:53 UTC, Whoistolu commented on spec/integrations/posts_index_spec.rb
> +  scenario 'Display user profile information and posts' do
- [ ] [REQUIRED] Kindly fix the following tests as they fail.
- Tests that asserts you can see the user's profile picture
- Tests that asserts you can see the user's username.
<img width="627" alt="Screenshot 2023-11-24 at 13 25 59" src="https://github.com/kazim110/blog_app/assets/58692590/79f72adc-7dcf-4811-b44d-5db295aca1c1">

2023-11-24 12:53 UTC, Whoistolu commented on spec/integrations/posts_index_spec.rb
> +  end
- [ ] [REQUIRED] For the User Post index page, kindly add the following tests because they are hard requirements:
- Tests that asserts you can see the number of posts the user has written
- Tests that asserts you can see a post's title
- Tests that asserts you can see some of the post's body.
- Tests that asserts you can see the first comments on a post.
- Tests that asserts you can see how many comments a post has.
- Tests that asserts you can see how many likes a post has.
- Tests that asserts you can see a section for pagination if there are more posts than fit on the view.
- Tests that redirects to the post's show page when you click on a post.

2023-11-24 12:53 UTC, Whoistolu commented on spec/integrations/posts_show_spec.rb
> +end
- [ ] [REQUIRED] Let' ensure that we are testing the cases provided in the project requirement properly. Here's a [capybara cheat sheet](https://gist.github.com/zhengjia/428105) that can help you.

Kindly add the following tests :
* Tests that asserts you can see the post's title.
* Tests that asserts you can see who wrote the post.
* Tests that asserts you can see how many comments it has.
* Tests that asserts you can see how many likes it has.
* Tests that asserts you can see the post body.
* Tests that asserts you can see the username of each commentor.
* Tests that asserts you can see the comment each commentor left.

- [ ] [OPTIONAL] I would like to advice that you consider breaking down your scenario into smaller, more focused tests. Each test should ideally focus on a specific aspect of the feature. For example, you could have separate tests for post details, comments, and the presence of the "New Comment" link.
- [ ] [OPTIONAL] Also, I will like you to consider making your expectations more descriptive. For example, instead of checking for the presence of "Post#1", you might check for the post's actual content or a more descriptive identifier.
``` ruby
expect(page).to have_content("Post Content: This is the content of the post")
```

2023-11-25 08:34 UTC, Abenezer-Tilahun commented on spec/integrations/users_index_spec.rb
> +end
Fixed.

2023-11-25 08:43 UTC, Abenezer-Tilahun commented on spec/integrations/users_show_spec.rb
> +end
Fixed.

2023-11-25 08:46 UTC, Abenezer-Tilahun commented on spec/integrations/posts_index_spec.rb
> +  scenario 'Display user profile information and posts' do
Fixed.

2023-11-25 08:53 UTC, Abenezer-Tilahun commented on spec/integrations/posts_index_spec.rb
> +  end
- [ Optional ]  Good Job for Implemented the suggested changes but as suggested by the previous reviewer to good practice to **consider breaking down your scenario into smaller, more focused tests. Each test should ideally focus on a specific aspect of the feature.** I strongly recommend you to consider these suggestion.

2023-11-25 08:53 UTC, Abenezer-Tilahun commented on spec/integrations/posts_index_spec.rb
> +  end
Fixed.

2023-11-25 09:04 UTC, Abenezer-Tilahun requested changes
Hi @kazim110 @Nessrine88 

Great work on making the changes requested by a previous reviewer 👏
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.
✔️ All Test cases are passing.
![image](https://github.com/kazim110/blog_app/assets/93598189/46e4230e-b563-4820-ad10-224bfcd9f7f7)

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-25 09:04 UTC, Abenezer-Tilahun commented on spec/integrations/posts_show_spec.rb
> +  end
- [ ] Good Job for Implemented the previous reviewer suggestion But as suggested by the previous reviewer Kindly I recommend you to add **Tests that asserts you can see how many likes it has.**, **Tests that asserts you can see the username of each commenter**.  **Tests that asserts you can see the comment each commenter left.** Kindly Implemented it's one basic project requirement.
 - [ Optional ]  Good Job for Implemented the suggested changes but as suggested by the previous reviewer to good practice to **consider breaking down your scenario into smaller, more focused tests. Each test should ideally focus on a specific aspect of the feature.** I strongly recommend you to consider these suggestion.

2023-11-25 11:21 UTC, prolajumokeoni approved these changes
Hi @kazim110 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Tests updated ✅ 
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-25 13:09 UTC, merged

2024-01-29 16:25 UTC, Ibizugbe commented
Hi @kazim110 👋🏼👋🏼👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

I understand this project has been approved previously, but because this is a pair-programing activity, you'll have to do it again with your current partner. If this was a solo project, it would have gone straight for approval. Hence, please kindly reach out to your current partner and work with Him/Her for this milestone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-01-29 16:47 UTC, Ibizugbe commented
Hi @kazim110 👋🏼👋🏼👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

I understand this project has been approved previously, but because this is a pair-programing activity, you'll have to do it again with your current partner. If this was a solo project, it would have gone straight for approval. Hence, please kindly reach out to your current partner and work with Him/Her for this milestone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

*Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.*

--------

Invalid Code Review Request *does not count* into the code reviews limit.